version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    command: node src/index.js
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/projectdb
      - JWT_SECRET=supersecret
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
    ports:
      - "3000:5173"
    depends_on:
      - backend

volumes:
  mongo-data:
